### ISSUE TITLE
Resource not found: carla_ego_vehicle

### ISSUE THREAD

**Issue by Promise93** [patrickcleeve2/safety_score#2]
Hello, I am very interested in this repo. What the version of carla and ros_bridge are you using?

**Comment by patrickcleeve2** [comment]
Hi @Promise93 , 

This was done on Ubuntu 18.04, ROS Melodic, and CARLA 0.9.12. 

I'm using an older version of carla_ros_bridge (https://github.com/carla-simulator/ros-bridge/tree/0.9.10.1) . So if you use that, it should work. 

If you want to use the latest, it seems it has now changed to use spawn_objects instead (https://github.com/carla-simulator/ros-bridge/blob/master/carla_ros_bridge/launch/carla_ros_bridge_with_example_ego_vehicle.launch), which is why it can't find carla_ego_vehicle. I would change line 3 in the [launch file] (https://github.com/patrickcleeve2/safety_score/blob/a30dc6223e734a8d7701c4111190cfc139a8677e/safety_score/launch/safety_score.launch#L3) to 

` <include file="$(find carla_ros_bridge)/launch/carla_ros_bridge_with_example_ego_vehicle_demo.launch" />`

You will also need to change the role_name to "hero" in that the carla_ros_bridge launch file. 

Hope that helps

**Comment by Promise93** [comment]
I used the carla_ros_bridge 0.9.10.1 . It worked. Thanks！
